CREATE TABLE VENDOR_QUALIFICATION_MASTER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VQF_REF_NO VARCHAR2(4000),
    MATERIAL_ITEM VARCHAR2(4000),
    DISPOSITION VARCHAR2(4000),
    SUPPLIER1_INFO VARCHAR2(4000),
    SUPPLIER2_INFO VARCHAR2(4000),
    SUPPLIER3_INFO VARCHAR2(4000),
    REMARK CLOB,
    CHECKED_BY VARCHAR2(50),
    CHECKED_DATE DATE,
    CREATED_BY VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    STATUS CHAR(1) DEFAULT '1'
);

CREATE TABLE VENDOR_QUALIFICATION_CRITERIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MASTER_ID NUMBER NOT NULL,
    CRITERIA VARCHAR2(255),
    RATING NUMBER(5,2),
    SUPPLIER1 VARCHAR2(255),
    SUPPLIER2 VARCHAR2(255),
    SUPPLIER3 VARCHAR2(255),
    CREATED_BY VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    STATUS CHAR(1) DEFAULT '1',
    CONSTRAINT FK_MASTER_ID FOREIGN KEY (MASTER_ID)
        REFERENCES VENDOR_QUALIFICATION_MASTER(ID)
        ON DELETE CASCADE
);

